CREATE TABLE users(
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(32) NOT NULL,
	password VARCHAR(64) NOT NULL,
	email VARCHAR(32) NOT NULL,
	role INT(4),
	level INT(4),
	created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);